[features]
seeds = false
skip-lint = false

[programs.devnet]
dataset_provenance = "6nevEtv1X6KV8BprxJdD5qJSAPkdi2tym2zZPrvxeqF7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
